### ISSUE TITLE
Re:  Project at Upwork

### ISSUE THREAD

**Issue by Marx-Melencio** [SuperDevMonk/Chess-Web-AI#1]
@SuperDevMonk   --  Hi Amir. This is about the Canadian real estate listings database project at Upwork. What's your email, so I can contact you directly? You can just delete this issue once I get your email. Thanks!

**Comment by SuperDevMonk** [comment]
interesting. my email amir.whasim@gmail.com

**Comment by Marx-Melencio** [comment]
Hi Amir,

I'm Marx Melencio. I'm the founder and B2B client acquisition strategist of
Grayscale Marketing Consultancy, the company in Upwork that posted the
project in Upwork. It's nice to meet you!  :)

How many hours is your estimate for completing the project that I posted in
Upwork? Please advise.

Thanks!

Best Regards,
Marx

On Thu, Jun 8, 2023 at 8:04 AM SuperDevMonk ***@***.***>
wrote:

> interesting. my email ***@***.***
>
> —
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>
--
Marx Melencio
Deep Learning Engineer & Computer Vision Researcher


*Mobile:  *+639178867294
*ARIA Research PTY, Ltd.* <https://ariaresearch.com.au> *(Sydney, AU)*

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
This message and/or the attached document/s contain information that may be
confidential and privileged. Unless you are the intended recipient (or
authorized to receive this message and/or the attached document/s for the
intended recipient), you may not use, copy, disseminate or disclose to
anyone the message and/or the attached document/s or any information
contained in the message and/or the attached document/s. If you have
received the message and/or the attached document/s in error, please advise
the sender by reply e-mail and delete the message, the attached document/s,
and/or any copy of the message and/or the attached document/s. Thank you
very much.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by Marx-Melencio** [comment]
Thanks, Amir. I just sent you an email.

**Comment by SuperDevMonk** [comment]
I already sent reply, I will wait at mail.google.com for you.
